# docker-compose for Pontoon development.
#
# Note: Requires docker-compose 1.27+.
services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    image: 715161504141.dkr.ecr.eu-west-1.amazonaws.com/pontoon:${VERSION}
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./pontoon:/app/pontoon
      - ./requirements:/app/requirements
      - ./translate:/app/translate
