# docker-compose for Pontoon development.
#
# Note: Requires docker-compose 1.10+.
version: '2.3'
services:
  server:
    image: local/pontoon
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"
      ]
    env_file:
      - .env
    depends_on:
      - postgresql
    ports:
      - '8000:8000'
      - '5678:5678'
    volumes:
      - ./pontoon:/app/pontoon
      - ./requirements:/app/requirements
      - ./tag-admin:/app/tag-admin
      - ./translate:/app/translate

  # Database
  postgresql:
    build:
      context: ./docker/postgres
      dockerfile: ./Dockerfile
    image: pontoon-postgresql:latest
    ports:
      - '5555:5432'
    environment:
      # Create the superuser account
      - POSTGRES_USER=pontoon
      - POSTGRES_PASSWORD=asdf
      - POSTGRES_DB=pontoon
    volumes:
      - pgdata:/var/lib/postgresql/data

# Persist database
volumes:
  pgdata: null
